service: coinpayments-ipn

provider:
  name: aws
  runtime: nodejs6.10
  stage: "1"
  region: us-east-1
  profile: perceptionz

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  receive:
    handler: handler.receive
    events:
      - http:
          path: /receive-ipn
          method: post
      - http:
          path: /receive-ipn
          method: get
